Convert docker-osg-build to GHA (Software-4683)
opensciencegrid/docker-osg-build pull request #7
Opened 2021-10-08 16:18 UTC by gesshin

2021-10-08 21:50 UTC, brianhlin requested changes
We'll need to enable the `devops` repo across the board in the Dockerfile. Other suggestions in-line

2021-10-08 21:50 UTC, brianhlin commented on Dockerfile
> +        yum-config-manager --enable osg-development; \
```suggestion
```

We don't need to tie the OSG repo to the OS version

2021-10-08 21:50 UTC, brianhlin commented on Dockerfile
> +        yum-config-manager --enable osg-minefield; \
```suggestion
```

Same as above

2021-10-11 16:17 UTC, RyanEweSeng commented on Dockerfile
> +        yum-config-manager --enable osg-development; \
Doesn't line 17 enable `devops` repo for all EL version?

2021-10-11 16:43 UTC, brianhlin approved these changes
LGTM

2021-10-11 16:43 UTC, brianhlin commented on Dockerfile
> +                   osg-build && \
There seems to be a trailing space that snuck in here. It's nbd but in the future, try to avoid unintentional whitespace changes as it makes the git history a bit more difficult to navigate when using tools like `git blame`

2021-10-11 16:44 UTC, merged